### ISSUE TITLE
[Linux] ERROR: ui/main.menu, line 4897: unknown menu keyword

### ISSUE THREAD

**Issue by greyspammer** [wolfetplayer/RealRTCW#104]
When I try to run the Linux binary, I get this output:
```
Sound initialization successful.
--------------------------------
^1ERROR: ui/main.menu, line 4897: unknown menu keyword {
^1ERROR: ui/main.menu, line 4899: unknown menu keyword group
^1ERROR: ui/main.menu, line 4899: unknown menu keyword credits
^1ERROR: ui/main.menu, line 4901: unknown menu keyword textfile
^1ERROR: ui/main.menu, line 4902: unknown menu keyword text/EnglishUSA/creditsp8_2.txt
^1ERROR: ui/main.menu, line 4902: unknown menu keyword textscale
^1ERROR: ui/main.menu, line 4902: unknown menu keyword .20
^1ERROR: ui/main.menu, line 4903: unknown menu keyword textfont
^1ERROR: ui/main.menu, line 4903: unknown menu keyword 2
^1ERROR: ui/main.menu, line 4906: unknown menu keyword decoration
^1ERROR: ui/main.menu, line 4907: unknown menu keyword autowrapped
--- Common Initialization Complete ---
```

Then a window pops up with nothing but a black screen in which the mouse cursor leaves a trace (like the cards in Windows Solitaire when you win).

![RealRTCW-Linux-Error01](https://github.com/wolfetplayer/RealRTCW/assets/3610613/48b8dc57-2fab-4603-9ea1-d5f62d15388c)

The Windows version with WINE on the same installation seems to work without issues though.

Shot in the dark: Could this be a line ending encoding problem in those text files?

System: Linux Mint 21.2, kernel 5.15.0, NVidia drivers 535.129.03.

**Comment by georgecoffey** [comment]
Same issue here, on KDE neon:
PRETTY_NAME="KDE neon 6.0"
NAME="KDE neon"
VERSION_ID="22.04"
VERSION="6.0"
VERSION_CODENAME=jammy
ID=neon
ID_LIKE="ubuntu debian"
