### ISSUE TITLE
How to write play.menu?

### ISSUE THREAD

**Issue by lnesuper** [wolfetplayer/RealRTCW#12]
How to base it “main.menu”， Write one “play.menu” and can run.

**Comment by wolfetplayer** [comment]
Can you elaborate?

**Comment by lnesuper** [comment]
In the z_realrtcw.pk3 file, unzip this. In the "ui" dir. Have main.menu, load.menu, ingame.menu, and more. In original file. Include play.menu. so how to write this. I try it, but not to run.

**Comment by wolfetplayer** [comment]
You dont need play.menu. It is included in main.menu in realrtcw

**Comment by lnesuper** [comment]
Yes, you are right. It is included in main.menu. But how to extract it? Can you give me a hint?

**Comment by wolfetplayer** [comment]
i think you need newgamemenu group

**Comment by lnesuper** [comment]
Think for your tips, I need try!
