### ISSUE TITLE
Script error with latest code

### ISSUE THREAD

**Issue by emileb** [wolfetplayer/RealRTCW#120]
Getting this script error with the latest code and v5.0 of the pk4 files. Is this something I have done wrong in compilation or something incompatible with the scripts?
Thanks!

![Screenshot_20240909_110231_Alpha Touch](https://github.com/user-attachments/assets/375155a9-3e10-428b-a787-267a6bb20c24)

**Comment by wolfetplayer** [comment]
Alright I drafted 5.0 release. Please use source code of this release. Further code changes are WIP and not fully compatible with latest public release of game files. ty.

**Comment by emileb** [comment]
Thank you, works with the 5.0 tag

**Comment by wolfetplayer** [comment]
was fixed in

https://github.com/wolfetplayer/RealRTCW/commit/b46304283fc98bb9ca22ad11ef360a5aaddca040
