### ISSUE TITLE
Compilation failed on Ubuntu 20.04

### ISSUE THREAD

**Issue by legluondunet** [wolfetplayer/RealRTCW#18]
Hello,
I just tried to compile RealRTCW from today's git and I obtained error at the end of compilation:

`LD build/release-linux-x86_64/main/ui.sp.x86_64.so
/usr/bin/x86_64-linux-gnu-ld.bfd.real : build/release-linux-x86_64/client/files.o : dans la fonction « FS_Startup » :
files.c:(.text+0x84ea) : référence indéfinie vers « Sys_SteamWorkshopPath »
collect2: error: ld returned 1 exit status
make[2]: *** [Makefile:2170 : build/release-linux-x86_64/RealRTCW.x86_64] Erreur 1
rm build/release-linux-x86_64/rend2/glsl/texturecolor_fp.c build/release-linux-x86_64/rend2/glsl/tonemap_vp.c build/release-linux-x86_64/rend2/glsl/ssao_fp.c build/release-linux-x86_64/rend2/glsl/ssao_vp.c build/release-linux-x86_64/rend2/glsl/dlight_vp.c build/release-linux-x86_64/rend2/glsl/calclevels4x_fp.c build/release-linux-x86_64/rend2/glsl/depthblur_vp.c build/release-linux-x86_64/rend2/glsl/pshadow_vp.c build/release-linux-x86_64/rend2/glsl/down4x_fp.c build/release-linux-x86_64/rend2/glsl/down4x_vp.c build/release-linux-x86_64/rend2/glsl/fogpass_fp.c build/release-linux-x86_64/rend2/glsl/tonemap_fp.c build/release-linux-x86_64/rend2/glsl/bokeh_vp.c build/release-linux-x86_64/rend2/glsl/calclevels4x_vp.c build/release-linux-x86_64/rend2/glsl/lightall_fp.c build/release-linux-x86_64/rend2/glsl/lightall_vp.c build/release-linux-x86_64/rend2/glsl/generic_vp.c build/release-linux-x86_64/rend2/glsl/bokeh_fp.c build/release-linux-x86_64/rend2/glsl/pshadow_fp.c build/release-linux-x86_64/rend2/glsl/fogpass_vp.c build/release-linux-x86_64/rend2/glsl/depthblur_fp.c build/release-linux-x86_64/rend2/glsl/texturecolor_vp.c build/release-linux-x86_64/rend2/glsl/shadowfill_fp.c build/release-linux-x86_64/rend2/glsl/shadowfill_vp.c build/release-linux-x86_64/rend2/glsl/dlight_fp.c build/release-linux-x86_64/rend2/glsl/generic_fp.c build/release-linux-x86_64/rend2/glsl/shadowmask_fp.c build/release-linux-x86_64/rend2/glsl/shadowmask_vp.c
make[2] : on quitte le répertoire « /home/legluondunet/Autres_applications/Jeux/Wolfenstein/Return to Wolfenstein Castle/RealRTCW/RealRTCW »
make[1]: *** [Makefile:1360 : targets] Erreur 2
make[1] : on quitte le répertoire « /home/legluondunet/Autres_applications/Jeux/Wolfenstein/Return to Wolfenstein Castle/RealRTCW/RealRTCW »
make: *** [Makefile:1278 : release] Erreur 2
`

> /usr/bin/x86_64-linux-gnu-ld.bfd.real : build/release-linux-x86_64/client/files.o :in function « FS_Startup » :
> files.c:(.text+0x84ea) : unknow reference to« Sys_SteamWorkshopPath

Thank you for your help.

**Comment by wolfetplayer** [comment]
Are you sure all files are up to date? I was getting this error before this commit was submitted:
https://github.com/wolfetplayer/RealRTCW/commit/fccf6b10f390f1cec3c4b72b04db03e877508659

Also you can try to compile no-steam version.(separate branch)

**Comment by legluondunet** [comment]
I downloaded git version ten minutes ago:
git clone https://github.com/wolfetplayer/RealRTCW

**Comment by wolfetplayer** [comment]
I see. Please use no-steam branch. It is 99.9% identical to main branch.

**Comment by legluondunet** [comment]
Compiled ok with nosteam branch.
This branch will be maintain in future?
Or you plan to merge the two branchs?

**Comment by wolfetplayer** [comment]
No steam branch will be maintained
