### ISSUE TITLE
Compile issues on macOS Catalina.

### ISSUE THREAD

**Issue by lorecast162** [wolfetplayer/RealRTCW#26]
I'm trying to compile on macOS Catalina using `make-macosx_xcode5.sh` (and then tried using `make`) but everytime it complains about not finding the `HMODULE` type, which is something to do with Cygwin, when compiling `code/steam/steam.c`.
I'm not going to use this with Steam (I just use my original copy's .pk3s) so I would like to disable anything to do with Steam, as vanilla ioquake3 and iortcw compile just fine on this machine making this an issue with this Steam integration code, not my machine/development environment.

**Comment by lorecast162** [comment]
Here is a log with the output of `make-macosx_xcode5.sh x86_64`:
```
Building in build/release-darwin-x86_64:
  PLATFORM: darwin
  ARCH: x86_64
  FILE_ARCH: x86_64
  VERSION: 3.1
  COMPILE_PLATFORM: darwin
  COMPILE_ARCH: x86_64
  HAVE_VM_COMPILED: true
  PKG_CONFIG: pkg-config
  CC: clang
  CXX: clang++

  CFLAGS:
    -arch x86_64 -DARCH_64 -Wall -arch x86_64 -mmacosx-version-min=10.6 -DMAC_OS_X_VERSION_MIN_REQUIRED=1060
    -fno-strict-aliasing -fno-common -pipe -D_THREAD_SAFE=1 -m64 -DNO_GZIP -Icode/zlib-1.2.11 -DUSE_INTERNAL_JPEG
    -Icode/jpeg-8c -DBUILD_FREETYPE -Icode/freetype-2.9/include -DFT2_BUILD_LIBRARY -Qunused-arguments
    -Qunused-arguments -DUSE_LOCAL_HEADERS -DPRODUCT_VERSION="3.1" -Wformat=2 -Wformat-security -Wno-format-nonliteral
    -Wstrict-aliasing=2 -Wmissing-format-attribute -Wdisabled-optimization -MMD -DNDEBUG -O3 -mfpmath=sse -ffast-math

  CLIENT_CFLAGS:
    -Icode/SDL2/include -DUSE_OPENAL -DUSE_OPENAL_DLOPEN -DUSE_VOIP -DUSE_CODEC_OPUS -DOPUS_BUILD -DHAVE_LRINTF
    -DFLOAT_APPROX -DUSE_ALLOCA -Icode/opus-1.2.1/include -Icode/opus-1.2.1/celt -Icode/opus-1.2.1/silk
    -Icode/opus-1.2.1/silk/float -Icode/opusfile-0.9/include -Icode/libogg-1.3.3/include -DUSE_RENDERER_DLOPEN
    -DUSE_MUMBLE -DUSE_BLOOM

  SERVER_CFLAGS:
    -DUSE_VOIP

  LDFLAGS:

  LIBS:
    -framework Cocoa

  CLIENT_LIBS:
    -framework IOKit code/libs/macosx/libSDL2-2.0.0.dylib

  Output:
    RealRTCW.x86_64
    renderer_sp_opengl1_x86_64.dylib
    renderer_sp_rend2_x86_64.dylib
    main/cgame.sp.x86_64.dylib
    main/qagame.sp.x86_64.dylib
    main/ui.sp.x86_64.dylib
    libSDL2-2.0.0.dylib
    libopenal.dylib

CC code/steam/steam.c
CC code/client/cl_cgame.c
code/steam/steam.c:13:1: error: unknown type name 'HMODULE'
HMODULE getLib(void){
^
code/steam/steam.c:18:2: error: use of undeclared identifier 'HMODULE'
        HMODULE mod = LoadLibraryA("steamcppwrappercustom64");;
        ^
code/steam/steam.c:20:9: error: use of undeclared identifier 'mod'
        return mod;
               ^
3 errors generated.
make[2]: *** [build/release-darwin-x86_64/client/steam.o] Error 1
make[2]: *** Waiting for unfinished jobs....
make[1]: *** [targets] Error 2
make: *** [release] Error 2
```

**Comment by lorecast162** [comment]
"Fixed" by using the `nosteam` release.
I still feel like this is a bad hack.
Is there a way to build without Steam but still using the `master` branch?

**Comment by lorecast162** [comment]
Alright I got it to work by using the `nosteam` branch. I also had another issue regarding the libstdc++. Fixed it by setting the `macosx-version-min` option to 10.9 as described by some compile errors.

**Comment by wolfetplayer** [comment]
Yeah, master branch equals Steam version of the mod which is windows only.

**Comment by palmerj** [comment]
I had to make a few more changes to get it going on 11.5 Big Sur:

```
diff --git a/Makefile b/Makefile
index 5000070..646f12e 100644
--- a/Makefile
+++ b/Makefile
@@ -497,7 +497,7 @@ ifeq ($(PLATFORM),darwin)
   endif
   ifeq ($(ARCH),x86_64)
     OPTIMIZEVM += -mfpmath=sse
-    BASE_CFLAGS += -arch x86_64 -mmacosx-version-min=10.6 \
+    BASE_CFLAGS += -arch x86_64 -mmacosx-version-min=10.9 \
       -DMAC_OS_X_VERSION_MIN_REQUIRED=1060
   endif
 
diff --git a/code/game/g_cmds.c b/code/game/g_cmds.c
index f8fc75f..c7c2601 100644
--- a/code/game/g_cmds.c
+++ b/code/game/g_cmds.c
@@ -29,6 +29,8 @@ If you have questions concerning this license or the applicable additional terms
 #include "g_local.h"
 #include "km_cvar.h"	// Knightmare added
 
+extern void Use_props_grammofon(gentity_t* ent, gentity_t* self, gentity_t* activator);
+
 /*
 ==================
 DeathmatchScoreboardMessage
diff --git a/make-macosx_xcode5.sh b/make-macosx_xcode5.sh
index a9d06c4..1f02cee 100755
--- a/make-macosx_xcode5.sh
+++ b/make-macosx_xcode5.sh
@@ -26,15 +26,15 @@ fi
 
 CC=clang
 CXX=clang++
-APPBUNDLE=iowolfsp.app
-BINARY=iowolfsp.${ARCH}
+APPBUNDLE=RealRTCW.app
+BINARY=RealRTCW.${ARCH}
 PKGINFO=APPLIOTCW
 ICNS=misc/iortcw.icns
 DESTDIR=build/release-darwin-${BUILDARCH}
 BASEDIR=main
 
 BIN_OBJ="
-	build/release-darwin-${BUILDARCH}/iowolfsp.${BUILDARCH}
+	build/release-darwin-${BUILDARCH}/RealRTCW.${BUILDARCH}
 "
 BASE_OBJ="
 	build/release-darwin-${BUILDARCH}/$BASEDIR/cgame.sp.${ARCH}.dylib
```

I can submit this as PR against `master-nosteam` if @wolfetplayer agrees. I haven't played all the way through yet, but first level is working

**Comment by palmerj** [comment]
Note for some reason I can't get the addins to load in the UI when I run the app bundle. My guess is something to do with the increased MacOS permissions when running from a bundle, but I've given full disk access permissions to the RealRTCW.app in the security and privacy settings. When I run RealRTCW.app/Contents/MacOS/RealRTCW.x86_64 from the terminal within bundle the addon show up.

**Comment by palmerj** [comment]
I've found a solution for getting the addons mods to load. I think it's to do with the way bundle path handling is managed. There seems to be some apple specific stripping of paths from the called bundle exe that is used to set the default basedir. This doesn't seem to work and I've reverted it to be the same as other platforms. When you do this double clicking the bundle or calling it from the command line both seem to work. Happy again to create a PR if this looks like a good solution.

**Comment by palmerj** [comment]
He's a x86_64 bundle if someone else needs one: [RealRTCW.app.zip](https://github.com/wolfetplayer/RealRTCW/files/6891388/RealRTCW.app.zip) You will need to drop retail and RealRTCW files into the Content/MacOS directory within the bundle (right click show "Show Package Context" to navigate into the bundle). After than you are good to go.

**Comment by palmerj** [comment]
@wolfetplayer are you open to receiving and merging the above patch as a PR?

**Comment by wolfetplayer** [comment]
Sure,go ahead.

**Comment by desmortum** [comment]
@palmerj, thanks. What would be the best way of getting retail copy so that I can unpack it? Will GOG or Steam versions be unpackable in macOS? Also, did you try it on Monterey yet?

**Comment by palmerj** [comment]
@desmortum sorry for the slow reply.

I have the original CD media for PC so I used that and installed official patches in a windows virtual machine and then used the resulting pak files for this mod. 

I haven't upgraded Monterey yet.
