### ISSUE TITLE
Possibility of uploading Mod DB release of nosteam version to GitHub

### ISSUE THREAD

**Issue by rea987** [wolfetplayer/RealRTCW#29]
Hi,

I play the mod via Luxtorpeda tool on Linux natively. The tool automates downloading and installing Linux version of games which aren't provided in Steam.

https://github.com/luxtorpeda-dev/luxtorpeda#luxtorpeda-dev
https://www.gamingonlinux.com/2021/01/try-out-luxtorpeda-a-steam-play-tool-to-run-games-in-native-game-engines

As Steam release of RealRTCW isn't compatible with nosteam version, data from Mod DB release is required. However, links provided by Mod DB are dynamics links which expire shortly after download, hence Luxtorpeda package of RealRTCW asks users to manually provide Mod DB version by themselves. In that case, would you mind uploading Mod DB release of nosteam version here in releases section on GitHub? Thank you!

https://www.moddb.com/mods/realrtcw-realism-mod/downloads/realrtcw-31
https://www.moddb.com/mods/realrtcw-realism-mod/downloads

Kind regards.

**Comment by wolfetplayer** [comment]
You need some alternative links for moddb content,right?

**Comment by rea987** [comment]
> You need some alternative links for moddb content,right?

Yes, exactly. Something static would be great.
