### ISSUE TITLE
Is realrtcw compatible with iortcw save files?

### ISSUE THREAD

**Issue by johndoe71rus** [wolfetplayer/RealRTCW#3]
When I load the save file from iortcw, I get an error.
```
---- Server Shutdown (Server crashed: G_LoadGame: entitynum out of range (1648, MAX = 1024)
```
I understand that there may be a difference in the availability of weapons, but in the modes of their weapons. 
  
Here's an error when start save a project 51.
https://i.imgur.com/foJABzJ.jpg
log 
https://paste.ubuntu.com/p/w2RHznyC5z/

**Comment by M0Rf30** [comment]
I've tested now on iortcw 1.51c-SP_GIT_ae0e2dbe-2018-07-15 linux-x86_64 lug 20 2018
I think it's not compatible. Also for me no success. RealRTCW is a modified ioRTCW engine
Here the log
https://pastebin.com/eFKnn7b7
