### ISSUE TITLE
Error while compiling on R-Pi 3B

### ISSUE THREAD

**Issue by CorsaXTD** [wolfetplayer/RealRTCW#31]
I'm using the https://github.com/wolfetplayer/RealRTCW/tree/master-nosteam but it gives the following error while compiling:

LD build/release-linux-arm/RealRTCW.arm
/usr/bin/ld: build/release-linux-arm/client/vm.o: in function `VM_Create':
vm.c:(.text+0xea4): undefined reference to `VM_Compile'
/usr/bin/ld: build/release-linux-arm/client/vm.o: in function `VM_Call':
vm.c:(.text+0x12dc): undefined reference to `VM_CallCompiled'
collect2: error: ld returned 1 exit status
make[2]: *** [Makefile:2302: build/release-linux-arm/RealRTCW.arm] Error 1
make[2]: Leaving directory '/home/rtcw/RealRTCW-master-nosteam'
make[1]: *** [Makefile:1464: targets] Error 2
make[1]: Leaving directory '/home/rtcw/RealRTCW-master-nosteam'
make: *** [Makefile:1378: release] Error 2

**Comment by wolfetplayer** [comment]
You can try to create issue here. Maybe iortcw maintainers could help.
https://github.com/iortcw/iortcw
