### ISSUE TITLE
Extended Training

### ISSUE THREAD

**Issue by wolfetplayer** [wolfetplayer/RealRTCW#37]
Script an actual training mission, where player learns how to move, jump, crouch, use various weapons and firemodes.
Might use those cut training texts.

**Comment by wolfetplayer** [comment]
Cooking something up...

**Comment by PanteraMax** [comment]
Sounds great!  And an extended training mission would be a fantastic way to introduce RtCW (and by extention, RealRtCW) to people who have never played before.

**Comment by wolfetplayer** [comment]
DONE IN 5.0
