### ISSUE TITLE
M1 Mac build starts but game crashes

### ISSUE THREAD

**Issue by gfelisberto** [wolfetplayer/RealRTCW#66]
I did a git clone of the repo and a `chmod +x make-macosx-app.sh make-macosx.sh` .
After a `./make-macosx.sh arm64` I copy the Steam pk3 files to the `build/release-darwin-arm64/main`as well as the files from `RealRTCW 3.3 ZIP` and started `./RealRTCW.arm64` .

The intro videos play normally and I can start the game. After the other intros when the wallpaper with the mission appears I get sent back to the console and in Activity Monitor I see the game marked in Red as Not Responding.

What other info/debug can I share?

**Comment by wolfetplayer** [comment]
What branch are you building? 
Try master-nosteam.
Master-steam is currently WIP

**Comment by gfelisberto** [comment]
I was running the `master-steam`. The `master-nosteam` does not build:

`
GAME_CC code/game/g_items.c
GAME_CC code/game/g_mem.c
code/game/g_cmds.c:1628:27: error: implicit declaration of function 'Use_props_grammofon' is invalid in C99 [-Werror,-Wimplicit-function-declaration]
                if (!traceEnt->is_dead) Use_props_grammofon(traceEnt, ent, ent);
                                        ^
1 error generated.
make[2]: *** [build/release-darwin-arm64/main/game/g_cmds.o] Error 1
`

**Comment by gfelisberto** [comment]
The MR fixes the build and now the game starts, but somethings are strange. When it starts I cannot see the gun on the floor, and after picking it up there is nothing on screen. Also sounds are kind of strange. I can try to record a screen capture of needed.

**Comment by gfelisberto** [comment]
Quick video https://youtu.be/Xpc8v71G5xg I used a camera because I do not have a loopback to grave video with audio

**Comment by gfelisberto** [comment]
I synced my repo to the main one and now both the -steam and -nosteam branches have the problem of the game crashing in the mission screen. Any debug info I can share?

**Comment by wolfetplayer** [comment]
Both branches are WIP. Probably need additionan game resources. Everything will be fine when 4.0 hits the deck.

**Comment by gfelisberto** [comment]
> I solved this problem by updating game resources

How did you do that?
