### ISSUE TITLE
Crash on 2nd launch

### ISSUE THREAD

**Issue by wolfetplayer** [wolfetplayer/RealRTCW#83]
Enter the game with fresh cfg
Change any setting
Quit
Try to relaunch - crash on desktop

I cant reproduce it.

**Comment by friggenbozo** [comment]
I fixed REALRTCW 4.0 after the update....
Instructions posted below:
easy peazy......

Bad news is your saves from before the update are junk.
Good news is ITS WORTH IT! Start over, the update is that good.
And don't bother with the 32 bit, it's toast.

After doing this the game runs with absolutely zero errors or glitches.
Graphics are better, lighting better, even the sound seems better.
What a beautiful game REALRTCW is!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

++++++++++++++++++++++++++++++++++++++
++++++++++++++++++++++++++++++++++++++

Problem: After update to version 4 Game runs once. If config file deleted, game runs once more but that's it.
__________________________________________
My system......
Windows 10, evga 2080 @ 2560 x 1440(native), 4790k, 16 gigs ram, steam. All drivers current.
-----------------------------------------------------------------

STEP 1:
Delete this file if it exists:
Documents/realrtcw 4.0/main/realrtcwconfigx64.cfg


STEP 2:
Run REALRTCW the game.


STEP 3:
Edit settings in game. DON't Miss any or you'll have to do this ALL over AGAIN!


STEP 4:
Exit game.


STEP 5:
Edit the config file Documents/realrtcw4.0/main/realrtcwconfigx64.cfg and delete the line:
seta in_joystick "0"
save the config file.


STEP 6:
Right click on that same config file and checkoff the box "read only".


ENJOY!
Whoever made this addon, THANK YOU!!!!!!!!!!!!!!!!!!!!!!

**Comment by wolfetplayer** [comment]
https://github.com/wolfetplayer/RealRTCW/commit/bdd555ff97c786d23116f415b5ab82dc8f3078c8
