### ISSUE TITLE
Weapons System

### ISSUE THREAD

**Issue by Anders1980** [wolfetplayer/RealRTCW#94]
Доброго времени суток. Можно ли систему файлов оружия, как в Вашем моде, встроить в чистый движок ioRtCW ? Заранее спасибо за ответ

**Comment by wolfetplayer** [comment]
Можно. Исходный код открыт, все наработки можно перенести.

**Comment by Anders1980** [comment]
Можешь это сделать, если нетрудно ? И собрать релиз ?

**Comment by wolfetplayer** [comment]
Я пас
