### ISSUE TITLE
Game crashes on Raspberry pi

### ISSUE THREAD

**Issue by olevenets2** [wolfetplayer/RealRTCW#96]
Hello, I have built a native engine on my Raspberry pi 4. The game is loading and I can change various options in the menu. But when I start a new game I get an error and the game closes:

`"Failed loading ./main/qagame.sp.aarch64.so: ./main/qagame.sp.aarch64.so: undefined symbol: G_GameSkillIntToStr"`

log https://paste.ee/p/cQ7bh

Can this be fixed somehow?

**Comment by ferrellsl** [comment]
> Hello, I have built a native engine on my Raspberry pi 4. The game is loading and I can change various options in the menu. But when I start a new game I get an error and the game closes:
> 
> `"Failed loading ./main/qagame.sp.aarch64.so: ./main/qagame.sp.aarch64.so: undefined symbol: G_GameSkillIntToStr"`
> 
> log https://paste.ee/p/cQ7bh
> 
> Can this be fixed somehow?

I get the same error on my Orange Pi 5 when attempting to start a game.

**Comment by ferrellsl** [comment]
> > Hello, I have built a native engine on my Raspberry pi 4. The game is loading and I can change various options in the menu. But when I start a new game I get an error and the game closes:
> > `"Failed loading ./main/qagame.sp.aarch64.so: ./main/qagame.sp.aarch64.so: undefined symbol: G_GameSkillIntToStr"`
> 
> > Can this be fixed somehow?
> 
> I get the same error on my Orange Pi 5 when attempting to start a game. My log is below.
> 
> [crashlog.txt](https://github.com/wolfetplayer/RealRTCW/files/11114662/crashlog.txt)

I think the error we're seeing is a Red Herring.  After copying over my config files from my Windows PC to my Pi 5 and giving them the correct names, I now get the error that's posted here:  https://github.com/wolfetplayer/RealRTCW/issues/92

So I'm starting to thing the problem is located in our config files and not with our build, but I'm unsure where to go from here.

**Comment by ferrellsl** [comment]
I just completed a successful build of RTCW on the Orange Pi 5 using this repo:  https://github.com/iortcw/iortcw

I recommend avoiding this repo as the code is broken and the maintainer isn't responding.

**Comment by wolfetplayer** [comment]
Code is not broken. You guys compiling a WIP branch which is not compatible with current public build of game resources. good luck.
